"""Add orchestration models

Revision ID: ec0f6e0912d2
Revises: c3d4e5f6g7h8
Create Date: 2026-05-16 22:03:53.069971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec0f6e0912d2'
down_revision: Union[str, None] = 'c3d4e5f6g7h8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_contexts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('system_command', sa.String(length=100), nullable=False),
    sa.Column('unified_risk_score', sa.Float(), nullable=True),
    sa.Column('trace', sa.JSON(), nullable=True),
    sa.Column('agent_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workbench_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_context_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('missing_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['execution_context_id'], ['execution_contexts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_audit_logs_category_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_is_middleware'), table_name='audit_logs')
    op.drop_column('items', 'priority')
    op.drop_column('items', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('priority', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_audit_logs_is_middleware'), 'audit_logs', ['is_middleware'], unique=False)
    op.create_index(op.f('ix_audit_logs_category_timestamp'), 'audit_logs', ['category', 'timestamp'], unique=False)
    op.drop_table('workbench_items')
    op.drop_table('execution_contexts')
    # ### end Alembic commands ###
